<MyGrid>
    GridLayout:
        rows:4
        size: root.width, root.height
        Image:
            source: "download7.jpg"
        GridLayout:
            rows:1

            Button:

                background_normal: "download.jpg"

            Button:

                background_normal: "download1.jpg"

            Button:

                background_normal: "download 2.jpg"
                border:(10,10,10,10)
